export const API_ENDPOINTS = {
  AUTH: {
    NONCE: '/v1.4/users/get-address-nonce',
    VERIFY_SIGNATURE: '/v1.6/users/verify-signature',
  },
  CATEGORY: {
    ALL: '/v1.5/get-all-categories',
  },
  CLAID_API: 'https://api.claid.ai/v1-beta1/image/edit',
  PRIVATE: {
    ADD_LIKE: '/v1.5/like/create',
    CHANGE_OFF_CHAIN_NFT_LOCATION_BY_ONE_TO_ANOTHER_COLLECTION: '/v1/collection/nft/update',
    RECEIVED_ITEM: 'v1/receive-my-item',
    CLAIM_WITH_ESCROW: '/v1/claim-with-escrow',

    CREATE_COLLECTIBLE: 'v1.10/user/create-collectible ',
    CREATE_COLLECTIBLE_VIEW: '/v1.4/create-collectible-view',
    CREATE_COLLECTION: '/v2/collections',
    CREATE_ESCROW_ORDER: '/v1/create-escrow-order',
    EDIT_COLLECTION: '/v1.1/edit-collection',
    EDIT_PROFILE: '/v1.5/users/update',
    ESCROW_BID_DETAIL: '/v1/escrow-bid-detail',
    EXPORT_SPACE: '/v2/space/create',
    GET_ALL_COLLECTIONS: '/v2/collections/all-for-create',
    GET_VAULT_ITEM_STATUS: '/v1/vault-item-status',
    GET_AUTHENTICATION_CREDIT: '/v1/authentication/remaining',
    GET_DASHBOARD_NFT: '/v2/user/dashboard/nft',
    GET_FAVORITES: '/v1.5/like/based/on/user/get',
    GET_SPACE: '/v2/space',
    GET_SPACE_NFTS: '/v2/space/nft',
    GENERATE_AI_IMAGES: '/v2/image_generation/generate-image',
    GET_AI_IMAGES: '/v2/image_generation/status',
    GET_GENERATED_AI_IMAGES: '/v2/image_generation/generated-images',
    GET_AI_REFRESH: '/v2/image_generation/refresh',
    GET_DIGITAL_NFTS: '/v2/user/nfts-wallet',
    GET_USER_DASHBOARD_STATS: '/v1/user/dashboard/stats',
    GET_USER_NFT: '/v1.5/users/get/my/collectibles/on/sale',
    GET_USER_NFT_LIST: '/v1/user/nft/list',
    GET_USER_PROFILE: '/v1.5/users/single/profile/get',
    NFT_HIDE_STATUS: 'v1.5/collectible/change-hide-status',
    POST_CHECK_FOLLOW: '/v1/user/follow/check',
    POST_FOLLOW: '/v1/user/follow',
    POST_UNFOLLOW: '/v1/user/unfollow',
    PUT_ON_SALE: '/v1.2/put-on-sale-item',
    SAVE_EVENT_BY_TRANSACTION: '/v1.4/collectible/save-event-by-transaction',
    SPACE_REMOVE_BACKGROUND: '/v2/space/remove-background',
    SPACE_REMOVE_BG_UPLOAD_IMAGE: '/v2/space/remove-background-with-upload',
    UPDATE_COLLECTION: '/v2/collections/update-address',
    UPDATE_COLLECTION_DETAIL: '/v2/collections',
    VALIDATE_CUSTOM_URL_COLLECTION: '/v2/collections/is-custom-url-valid',
  },
  PUBLIC: {
    EXPLORE: '/v1.7/explore/list/get',
    GET_BEST_SPACES: '/v1/homepage/space',
    GET_LATEST_SPACES: '/v2/space/latest',
    GET_COLLECTION_DETAILS: '/v2/collections/details',
    GET_FOLLOWER: '/v1/user/follow/list',
    GET_NFT_DETAILS_BY_COLLECTION_ADDRESS: 'v1.2/collectibles/by-collection',
    GET_SINGLE_HISTORY_NFT: '/v1.6/collectible/history/get',
    GET_SINGLE_NFT: '/v1.6/collectible/nft/single/page/get',
    GET_SPACE_BACKGROUND_COLORS: '/v2/space/background-color',
    GET_SPACE_BACKGROUND_TEMPLATES: '/v2/space/background-template',
    GET_SPACE_BORDERS: '/v2/space/border',
    GET_SPACE_ELEMENT_LIGHTINGS: '/v2/space/element-lighting',
    GET_SPACE_ELEMENT_OBJECTS: '/v2/space/element-object',
    LIVE_AUCTIONS_NFT_LIST: '/v2/auctions/live',
    META: {
      PRODUCT: '/v1/meta/product',
      PROFILE: '/v1/meta/profile',
    },
    MOST_VIEWED_NFT_LIST: '/v1.6/most-viewed-collectibles',
    PREV_SALES_LIST: '/v1.1/previous-sales',
    PROFILE_REACTION: 'v1/profile-reaction',
    RECENT_AUCTIONS_NFT_LIST: '/v2/auctions/recent',
    USD_RATES: '/v1.6/get-usd-rate',
  },
} as const

export const QUERIES = {
  AUTH: {
    NONCE: 'get-user-nonce',
    VERIFY_SIGNATURE: 'verify-signature',
  },
  CATEGORY: {
    ALL: 'get-all-categories',
  },
  PRIVATE: {
    ADD_LIKE: 'add_like',
    CHANGE_OFF_CHAIN_NFT_LOCATION_BY_ONE_TO_ANOTHER_COLLECTION: 'collection_nft_update',
    CREATE_COLLECTIBLE: 'user_create_collectible ',
    CREATE_COLLECTION: 'collection_create',
    EDIT_COLLECTION: 'edit_collection',
    GET_ALL_COLLECTIONS: 'get_all_collections_for_create',
    GET_DASHBOARD_NFT: 'user_dashboard_nft',
    GET_DIGITAL_NFTS: '/v2/user/nfts-wallet',
    GET_FAVORITES: 'like_based_on_user_get',
    GET_SPACE: '/v1/space',
    GET_SPACE_NFTS: '/v1/space-nft-list',
    GET_TOKEN_RATE: 'get-token-rate',
    GET_GENERATED_AI_IMAGES: '/v2/image_generation/generated-images',
    GET_USER_AUTHENTICATION_CREDIT: 'get_user_authentication_credit',
    GET_USER_BALANCES: 'get-user-balances',
    GET_USER_DASHBOARD_STATS: 'v1_user_dashboard_stats',
    GET_USER_NFT: '/v1.5/users/get/my/collectibles/on/sale',
    GET_USER_NFT_LIST: 'user_nft_list',
    GET_USER_PROFILE: 'v1.5/users/single/profile/get',
    GET_VAULT_ITEM_STATUS: 'v1/vault-item-status',
    POST_CHECK_FOLLOW: 'user_follow_check',
    POST_FOLLOW: 'user_follow',
    POST_UNFOLLOW: 'user_unfollow',
    UPDATE_COLLECTION: 'update_collection_address',
    VALIDATE_CUSTOM_URL_COLLECTION: 'collection_is_custom_url_valid',
  },
  PUBLIC: {
    COLLECTION: {
      GET: 'get-collection-details',
    },
    EXPLORE: 'get-explore-nft-list',
    GET_BEST_SPACES: 'get-best-spaces',
    GET_LATEST_SPACES: 'get-latest-spaces',
    GET_COLLECTION_DETAILS: 'collection_details',
    GET_FOLLOWER: 'user_follow_list',
    GET_NFT_DETAILS_BY_COLLECTION_ADDRESS: 'collectibles_by_collection',
    GET_SINGLE_HISTORY_NFT: 'get_single_history_nft',
    GET_SINGLE_NFT: 'get-single-nft',
    GET_SPACE_BACKGROUND_COLORS: '/v1/space-background-color',
    GET_SPACE_BACKGROUND_TEMPLATES: '/v1/space-background-template',
    GET_SPACE_BORDERS: '/v1/space-border',
    GET_SPACE_ELEMENT_LIGHTINGS: '/v1/space-element-lighting',
    GET_SPACE_ELEMENT_OBJECTS: '/v1/space-element-object',
    LIVE_AUCTIONS_NFT_LIST: 'get-live-auctions-nft-list',
    MOST_VIEWED_NFT_LIST: 'get-most-viewed-nft-list',
    NFT: {
      GET_ALL_BY_COLLECTION: 'get-nfts-by-collection',
    },
    PREV_SALES_LIST: 'get-prev-sales-list',
    PROFILE_REACTION: 'profile_reaction',
    RECENT_AUCTIONS_NFT_LIST: 'get-recent-auctions-nft-list',
  },
  TOKEN: {
    GET_BALANCE: 'get-token-balances',
  },
} as const
